/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SkypeBot;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author zain
 */
public class historyFrame extends javax.swing.JFrame
{
    private Scanner readFile;
    /**
     * Creates new form historyFrame
     */
    public historyFrame()
    {
        initComponents();
        
        // for conversation area auto scrolling down
        
    }
    
    public historyFrame(String lastData,String userID)
    {
        this();
        
        
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                JFrame historyFrame=new historyFrame();
                historyFrame.setVisible(true);
                historyFrame.setTitle(userID+" History");
                
                
                JTextArea textArea=new JTextArea(lastData);
                
                
                JScrollPane scroll=new JScrollPane(textArea);
                
                
                DefaultCaret caret = (DefaultCaret) textArea.getCaret();
                caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
                
                historyFrame.add(scroll);
                
                setMinimumSize(new Dimension(650, 500));
                 
                historyFrame.setVisible(true);
                
            }
             
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        setSize(new java.awt.Dimension(350, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
